// automatically generated by the FlatBuffers compiler, do not modify

package io.uninspired.madworld.core.network.protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PMove extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static PMove getRootAsPMove(ByteBuffer _bb) { return getRootAsPMove(_bb, new PMove()); }
  public static PMove getRootAsPMove(ByteBuffer _bb, PMove obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PMove __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int playerId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public io.uninspired.madworld.core.network.protocol.Vec2 to() { return to(new io.uninspired.madworld.core.network.protocol.Vec2()); }
  public io.uninspired.madworld.core.network.protocol.Vec2 to(io.uninspired.madworld.core.network.protocol.Vec2 obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startPMove(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPlayerId(FlatBufferBuilder builder, int playerId) { builder.addInt(0, playerId, 0); }
  public static void addTo(FlatBufferBuilder builder, int toOffset) { builder.addStruct(1, toOffset, 0); }
  public static int endPMove(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PMove get(int j) { return get(new PMove(), j); }
    public PMove get(PMove obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

