// automatically generated by the FlatBuffers compiler, do not modify

package io.uninspired.madworld.core.network.protocol;

@SuppressWarnings("unused")
public final class PacketType {
  private PacketType() { }
  public static final int TELEPORT = 0;
  public static final int MOVE = 1;
  public static final int JOIN = 2;
  public static final int GRID = 3;

  public static final String[] names = { "TELEPORT", "MOVE", "JOIN", "GRID", };

  public static String name(int e) { return names[e]; }
}

