// automatically generated by the FlatBuffers compiler, do not modify

package io.uninspired.madworld.core.network.protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PGamePacket extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static PGamePacket getRootAsPGamePacket(ByteBuffer _bb) { return getRootAsPGamePacket(_bb, new PGamePacket()); }
  public static PGamePacket getRootAsPGamePacket(ByteBuffer _bb, PGamePacket obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PGamePacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public io.uninspired.madworld.core.network.protocol.PTeleport pTeleport() { return pTeleport(new io.uninspired.madworld.core.network.protocol.PTeleport()); }
  public io.uninspired.madworld.core.network.protocol.PTeleport pTeleport(io.uninspired.madworld.core.network.protocol.PTeleport obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public io.uninspired.madworld.core.network.protocol.PMove pMove() { return pMove(new io.uninspired.madworld.core.network.protocol.PMove()); }
  public io.uninspired.madworld.core.network.protocol.PMove pMove(io.uninspired.madworld.core.network.protocol.PMove obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public io.uninspired.madworld.core.network.protocol.PJoin pJoin() { return pJoin(new io.uninspired.madworld.core.network.protocol.PJoin()); }
  public io.uninspired.madworld.core.network.protocol.PJoin pJoin(io.uninspired.madworld.core.network.protocol.PJoin obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public io.uninspired.madworld.core.network.protocol.PGrid pGrid() { return pGrid(new io.uninspired.madworld.core.network.protocol.PGrid()); }
  public io.uninspired.madworld.core.network.protocol.PGrid pGrid(io.uninspired.madworld.core.network.protocol.PGrid obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createPGamePacket(FlatBufferBuilder builder,
      int type,
      int pTeleportOffset,
      int pMoveOffset,
      int pJoinOffset,
      int pGridOffset) {
    builder.startTable(5);
    PGamePacket.addPGrid(builder, pGridOffset);
    PGamePacket.addPJoin(builder, pJoinOffset);
    PGamePacket.addPMove(builder, pMoveOffset);
    PGamePacket.addPTeleport(builder, pTeleportOffset);
    PGamePacket.addType(builder, type);
    return PGamePacket.endPGamePacket(builder);
  }

  public static void startPGamePacket(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addByte(0, (byte) type, (byte) 0); }
  public static void addPTeleport(FlatBufferBuilder builder, int pTeleportOffset) { builder.addOffset(1, pTeleportOffset, 0); }
  public static void addPMove(FlatBufferBuilder builder, int pMoveOffset) { builder.addOffset(2, pMoveOffset, 0); }
  public static void addPJoin(FlatBufferBuilder builder, int pJoinOffset) { builder.addOffset(3, pJoinOffset, 0); }
  public static void addPGrid(FlatBufferBuilder builder, int pGridOffset) { builder.addOffset(4, pGridOffset, 0); }
  public static int endPGamePacket(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishPGamePacketBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedPGamePacketBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PGamePacket get(int j) { return get(new PGamePacket(), j); }
    public PGamePacket get(PGamePacket obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

